// Independent coverage checker for the market-aligned three-agent theorem
// (written separately; shares no code with verification/coverage15/verify_cover.cpp).
//
// Setting: m = 15 goods, agent 1's ranking normalized to the identity, market
// triples an arbitrary unordered partition Q into five triples. Candidates are
// ALL market-block-balanced allocations (6^5 = 7776) that satisfy agent 1's
// SD-EF1 prefix constraints; agent 0 is protected by market-block balance.
// No own-bundle or shift restriction, no learned cores, no symmetry.
//
// Q is covered iff for every ranking sigma_2 some candidate satisfies all of
// agent 2's prefix constraints |A_j cap U| <= |A_2 cap U| + 1 (j = 0, 1).
// Exact recursion on states (T, L): T = current prefix set, L = candidates that
// passed agent 2's constraints at every earlier prefix of the current branch.
//   covered(T, L) = L nonempty and (some A in L is permanently safe at T, or
//                   covered(T+g, L & Good(T+g)) for every g not in T).
// Permanently safe: |A_2 cap T| >= 4 (all bundles have 5 goods), which is exact:
// the worst continuation adds the rest of A_j and nothing of A_2.
// Memo: exact (T, L) keys (full bitset comparison), per partition.
//
// Symmetry: the group H of order 12 generated by swapping goods 0,1 and
// permuting goods 12,13,14 maps the agent-1-feasible market-balanced allocations
// of Q bijectively onto those of the image partition. Proof: H fixes every
// identity prefix except those of length 1, 13 and 14. Length 1 is always
// satisfied. Let a_i be agent i's number of goods among 12..14. Prefix 12 gives
// a_1 <= a_j + 1 for j = 0, 2, hence a_1 <= 1 (a_1 = 2 would leave some a_j = 0).
// For a prefix 12 + R with R inside {12,13,14} and r_i = |A_i cap R| <= a_i, the
// constraint 5 - a_j + r_j <= 6 - a_1 + r_1 then holds because its left side is
// at most 5 and its right side at least 5. So prefixes 13, 14 are implied. Coverage
// over all sigma_2 is invariant under relabeling. With mode "orbits" only the
// minimum-index member of each H-orbit is checked, and orbit sizes are summed.
//
// Usage: cover15_ours <worker> <nworkers> [limit] [orbits]
// Processes partition indices i with i % nworkers == worker (i < limit).
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <unordered_map>
#include <vector>
#include <string>
#include <array>
#include <algorithm>
using namespace std;
static const int M = 15, NU = 1 << M;

static int W;                                   // words per candidate bitset
static vector<uint64_t> goodTab, safeTab;       // [U * W + w]
static long long calls;

struct Key {
    uint32_t T; vector<uint64_t> L;
    bool operator==(const Key& o) const { return T == o.T && L == o.L; }
};
struct KH {
    size_t operator()(const Key& k) const {
        uint64_t h = k.T * 0x9E3779B97F4A7C15ULL;
        for (uint64_t x : k.L) { h ^= x + 0x9E3779B97F4A7C15ULL + (h << 6) + (h >> 2); }
        return h;
    }
};
static unordered_map<Key, bool, KH> memo;

static bool covered(uint32_t T, const vector<uint64_t>& L) {
    ++calls;
    bool any = false;
    const uint64_t* S = &safeTab[(size_t)T * W];
    for (int w = 0; w < W; ++w) { if (L[w]) any = true; if (L[w] & S[w]) return true; }
    if (!any) return false;
    Key key{T, L};
    auto it = memo.find(key);
    if (it != memo.end()) return it->second;
    bool res = true;
    vector<uint64_t> C(W);
    for (int g = 0; g < M && res; ++g) {
        if (T >> g & 1) continue;
        uint32_t U = T | (1u << g);
        const uint64_t* G = &goodTab[(size_t)U * W];
        for (int w = 0; w < W; ++w) C[w] = L[w] & G[w];
        if (!covered(U, C)) res = false;
    }
    memo.emplace(move(key), res);
    return res;
}

int main(int argc, char** argv) {
    int worker = atoi(argv[1]), nw = atoi(argv[2]);
    long long limit = argc > 3 ? atoll(argv[3]) : (1LL << 62);
    bool orbits = argc > 4 && string(argv[4]) == "orbits";
    // enumerate partitions: smallest remaining good + two partners
    vector<array<int, 15>> parts;  // triple id per good
    {
        array<int, 15> tri; tri.fill(-1);
        std::vector<array<int,15>>* out = &parts;
        struct Rec { static void go(array<int,15>& tri, int k, vector<array<int,15>>& out) {
            int a = -1; for (int g = 0; g < M; ++g) if (tri[g] < 0) { a = g; break; }
            if (a < 0) { out.push_back(tri); return; }
            for (int b = a + 1; b < M; ++b) if (tri[b] < 0)
                for (int c = b + 1; c < M; ++c) if (tri[c] < 0) {
                    tri[a] = tri[b] = tri[c] = k; go(tri, k + 1, out); tri[a] = tri[b] = tri[c] = -1;
                }
        } };
        Rec::go(tri, 0, *out);
    }
    if ((long long)parts.size() != 1401400) { fprintf(stderr, "bad count %zu\n", parts.size()); return 1; }
    // encoding of a partition: sorted triple masks
    auto encode = [](const array<int, 15>& tri) {
        uint32_t mk[5] = {0, 0, 0, 0, 0};
        for (int g = 0; g < M; ++g) mk[tri[g]] |= 1u << g;
        std::sort(mk, mk + 5);
        string e; for (int k = 0; k < 5; ++k) e += to_string(mk[k]) + ",";
        return e;
    };
    unordered_map<string, long long> indexOf;
    vector<array<int, 15>> group;  // good permutations
    if (orbits) {
        for (long long i = 0; i < (long long)parts.size(); ++i) indexOf[encode(parts[i])] = i;
        int f[6][3] = {{12,13,14},{12,14,13},{13,12,14},{13,14,12},{14,12,13},{14,13,12}};
        for (int sw = 0; sw < 2; ++sw) for (int p = 0; p < 6; ++p) {
            array<int, 15> phi; for (int g = 0; g < M; ++g) phi[g] = g;
            if (sw) { phi[0] = 1; phi[1] = 0; }
            for (int k = 0; k < 3; ++k) phi[12 + k] = f[p][k];
            group.push_back(phi);
        }
    }
    long long weightSum = 0, reps = 0;
    static const int perm[6][3] = {{0,1,2},{0,2,1},{1,0,2},{1,2,0},{2,0,1},{2,1,0}};
    long long done = 0, fails = 0, totCalls = 0, minC = 1 << 30, maxC = 0, totStates = 0;
    for (long long idx = worker; idx < (long long)parts.size() && idx < limit; idx += nw) {
        const auto& tri = parts[idx];
        if (orbits) {
            bool isMin = true; std::vector<long long> imgs;
            for (auto& phi : group) {
                array<int, 15> t2; for (int g = 0; g < M; ++g) t2[phi[g]] = tri[g];
                long long j = indexOf.at(encode(t2));
                if (j < idx) { isMin = false; break; }
                imgs.push_back(j);
            }
            if (!isMin) continue;
            std::sort(imgs.begin(), imgs.end());
            weightSum += std::unique(imgs.begin(), imgs.end()) - imgs.begin(); ++reps;
        }
        int mem[5][3], cnt[5] = {0};
        for (int g = 0; g < M; ++g) mem[tri[g]][cnt[tri[g]]++] = g;
        // candidates: owner masks per agent
        vector<array<uint32_t, 3>> cand;
        for (int code = 0; code < 7776; ++code) {
            array<uint32_t, 3> A = {0, 0, 0}; int c = code;
            for (int b = 0; b < 5; ++b) { int p = c % 6; c /= 6;
                for (int k = 0; k < 3; ++k) A[perm[p][k]] |= 1u << mem[b][k]; }
            // agent 1, identity ranking
            bool ok = true; int n0 = 0, n1 = 0, n2 = 0;
            for (int g = 0; g < M && ok; ++g) {
                n0 += A[0] >> g & 1; n1 += A[1] >> g & 1; n2 += A[2] >> g & 1;
                if (n0 > n1 + 1 || n2 > n1 + 1) ok = false;
            }
            if (ok) cand.push_back(A);
        }
        int n = cand.size();
        W = (n + 63) / 64;
        goodTab.assign((size_t)NU * W, 0); safeTab.assign((size_t)NU * W, 0);
        for (uint32_t U = 0; U < (uint32_t)NU; ++U)
            for (int a = 0; a < n; ++a) {
                int c0 = __builtin_popcount(cand[a][0] & U), c1 = __builtin_popcount(cand[a][1] & U),
                    c2 = __builtin_popcount(cand[a][2] & U);
                if (c0 <= c2 + 1 && c1 <= c2 + 1) goodTab[(size_t)U * W + a / 64] |= 1ULL << (a % 64);
                if (c2 >= 4) safeTab[(size_t)U * W + a / 64] |= 1ULL << (a % 64);
            }
        vector<uint64_t> L(W, 0);
        for (int a = 0; a < n; ++a) L[a / 64] |= 1ULL << (a % 64);
        memo.clear(); calls = 0;  // the memo is also flushed below if it grows too large
        bool ok = covered(0, L);
        ++done; totCalls += calls; totStates += memo.size();
        if (n < minC) minC = n; if (n > maxC) maxC = n;
        if (!ok) { ++fails; printf("FAIL %lld\n", idx); fflush(stdout); }
        if (done % 2000 == 0) { fprintf(stderr, "worker %d done %lld\n", worker, done); }
    }
    printf("{\"worker\":%d,\"nworkers\":%d,\"partitions\":%lld,\"uncovered\":%lld,\"recursive_calls\":%lld,"
           "\"memo_states\":%lld,\"min_candidates\":%lld,\"max_candidates\":%lld,"
           "\"orbit_mode\":%d,\"representatives\":%lld,\"orbit_weight_sum\":%lld}\n",
           worker, nw, done, fails, totCalls, totStates, minC, maxC, (int)orbits, reps, weightSum);
}
