"""Generate the LaTeX tables of the supplement's Appendix B from results/n2_cover_experiments.json
(so that no number in those tables is typed by hand)."""
import json
import os
from collections import Counter

here = os.path.dirname(os.path.abspath(__file__))
d = json.load(open(os.path.join(here, "..", "results", "n2_cover_experiments.json")))


def fmt(n):
    return f"{n:,}".replace(",", "{,}")


rows = []
for r in d["E1_additive_two_cover"]:
    b = r["climb_best"]
    rows.append(f"{r['m']} & {fmt(r['random_hard_profiles'])} & {fmt(r['random_trials'])} & {len(r['profiles_without_2cover'])} "
                f"& {fmt(r['climb_restarts'])} & {b['disjoint_pairs']} & {'yes' if b['two_cover'] else 'NO'}\\\\")
t1 = ("\\begin{table}[h]\n\\centering\\small\n\\begin{tabular}{@{}rrrrrrr@{}}\n\\toprule\n"
      "$m$ & hard profiles & random pairs drawn & without 2-cover & climb restarts & min.\\ disjoint pairs & 2-cover there\\\\\n\\midrule\n"
      + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n"
      "\\caption{Additive markets, two agents (E1). For each $m$, 100 random hard profiles were drawn and a covering pair of subjectively SD-EF1 "
      "allocations was searched among all pairs with disjoint defect masks (necessary) and verified by linear programming. "
      "The hill-climb minimizes the number of pairs with disjoint defect masks over profiles; the last two columns report the best profile it found "
      "(fewest such pairs) and whether it still has a covering pair. No profile without a covering pair was found.}\n"
      "\\label{tab:e1}\n\\end{table}\n")

rows = []
for r in d["E2_monotone_exact_min_cover"]:
    c = Counter(p["min_cover"] for p in r["profiles"])
    rows.append(f"{r['m']} & {len(r['profiles'])} & {r['ceil_m_over_2']} & " + ", ".join(f"{k}: {v}" for k, v in sorted(c.items(), key=lambda kv: str(kv[0]))) +
                f" & {min(p['S'] for p in r['profiles'])}--{max(p['S'] for p in r['profiles'])}\\\\")
t2 = ("\\begin{table}[h]\n\\centering\\small\n\\begin{tabular}{@{}rrrll@{}}\n\\toprule\n"
      "$m$ & profiles & $\\lceil m/2\\rceil$ & minimum cover size (count) & $|\\mathcal S|$\\\\\n\\midrule\n"
      + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n"
      "\\caption{Exact minimum cover of all inclusion-monotone valuations by subjectively SD-EF1 allocations (E2), on sampled hard profiles; "
      "$|\\mathcal S|$ is the number of subjectively SD-EF1 allocations of the profile.}\n\\label{tab:e2}\n\\end{table}\n")

rows = []
for r in d["E3_reversal_path_is_exact_cover"]:
    ps = r["profiles"]
    rows.append(f"{r['m']} & {len(ps)} & {sorted(set(p['market_classes'] for p in ps))[0]} & "
                f"{sum(p['path_in_S'] for p in ps)}/{len(ps)} & {sum(p['path_is_cover'] for p in ps)}/{len(ps)} & "
                f"{sum(p['every_member_necessary'] for p in ps)}/{len(ps)}\\\\")
t3 = ("\\begin{table}[h]\n\\centering\\small\n\\begin{tabular}{@{}rrrrrr@{}}\n\\toprule\n"
      "$m$ & profiles & market classes on the path & path $\\subseteq\\mathcal S$ & path is a cover & every member necessary\\\\\n\\midrule\n"
      + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n"
      "\\caption{The reversal path of Theorem 3.1 on sampled hard profiles (E3), verified by exact linear programs over all monotone valuations. "
      "``Market classes'' counts the path's allocations up to exchanging the two bundles.}\n\\label{tab:e3}\n\\end{table}\n")

e4 = d["E4_disjoint_defect_route_fails_for_two_agents"]
hdr = "% generated by gen_tables.py from results/n2_cover_experiments.json; do not edit by hand\n"
for name, t in (("tables_e1.tex", t1), ("tables_e2.tex", t2), ("tables_e3.tex", t3)):
    open(os.path.join(here, name), "w").write(hdr + t)
# E5: covering pair on the reversal path
rows = []
for r in d.get("E5_covering_pair_on_reversal_path", []):
    rows.append(f"{r['m']} & {r['profiles']} & {r['with_covering_pair_on_path']}\\\\")
t5 = ("\\begin{table}[h]\n\\centering\\small\n\\begin{tabular}{@{}rrr@{}}\n\\toprule\n"
      "$m$ & sampled hard profiles & with a covering pair among the path's allocations\\\\\n\\midrule\n"
      + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n"
      "\\caption{Additive markets (E5): a covering pair of subjectively SD-EF1 allocations need not lie on the reversal path.}\n\\label{tab:e5}\n\\end{table}\n")
open(os.path.join(here, "tables_e5.tex"), "w").write(hdr + t5)
print("wrote tables_e1..e5.tex")
